spring.application.name=ms-room
server.port=8081

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.root=INFO

spring.output.ansi.enabled=ALWAYS

spring.datasource.url=jdbc:postgresql:db.holjwnvmlbywbdxdbgic.supabase.co:5432/postgres
spring.datasource.username=postgres.holjwnvmlbywbdxdbgic
spring.datasource.password=!Apionix010519
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=never
spring.sql.init.data-locations=

spring.jpa.defer-datasource-initialization=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=bd_

spring.flyway.enabled=true
spring.flyway.default-schema=bd_habitaciones
spring.flyway.schemas=bd_habitaciones
spring.flyway.locations=classpath:db/migration