spring.application.name=booking
server.port=8082

# Reemplaza TU_PROYECTO_RESERVAS y TU_PASSWORD con las credenciales de la DB de Reservas en Supabase
spring.datasource.url=jdbc:postgresql://db.TU_PROYECTO_RESERVAS.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=TU_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Flyway creará la tabla en el esquema público de esta base de datos independiente
spring.flyway.schemas=public