CREATE SCHEMA IF NOT EXISTS bd_reservas;

-- Creamos la tabla reservas dentro de nuestro esquema lógico asignado
CREATE TABLE IF NOT EXISTS bd_reservas.reservas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    habitacion_id BIGINT NOT NULL,
    huesped_id BIGINT NOT NULL,
    fecha_entrada DATE NOT NULL,
    fecha_salida DATE NOT NULL,
    monto_total DOUBLE PRECISION NOT NULL,
    estado VARCHAR(50) NOT NULL
);