spring.application.name=guest
server.port=8082

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.root=INFO

spring.output.ansi.enabled=

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=

spring.sql.init.mode=
spring.sql.init.data-locations=

spring.jpa.defer-datasource-initialization=
spring.jpa.properties.hibernate.format_sql=
spring.jpa.hibernate.ddl-auto=
spring.jpa.properties.hibernate.dialect=
spring.jpa.show-sql=
spring.jpa.properties.hibernate.default_schema=

spring.flyway.enabled=
spring.flyway.default-schema=
spring.flyway.schemas=
spring.flyway.locations=